version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=t3sesame
      - DB_PASSWORD=password
      - DB_NAME=t3sesame
      - SESSION_SECRET=your-super-secret-session-key-change-in-production
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./static:/root/static

  postgres:
    image: pgvector/pgvector:pg17 
    environment:
      - POSTGRES_USER=t3sesame
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=t3sesame
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U t3sesame"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: